[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ie_bike_model"
author = "teamc"
classifiers = ["License :: OSI Approved :: MIT License"]

